<?php
/**
 * Implements hook_theme().
 */
function wraith_theme() {
  return array(
    'wraith_capture' => array(
      'variables' => array(
        'links' => array(),
        'current_domain' => NULL,
        'new_domain' => NULL
      )
    )
  );
}

function wraith_query_alter(Drupal\Core\Database\Query\AlterableInterface $query) {
  if ($query->hasTag('wraith_random')) {
    $query->orderRandom();
  }
}